name: Build Linux

# 📜 https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.8"
      - name: Build debug version
        run: |
          swift build
