---
name: Build Linux

# 📜 https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build debug version
        run: |
          swift build --target Blocks

# TODO: Find a way for tests to work in spite of `ObjectiveBlocks`
