name: Build macOS

# 📜 https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.8"
      - name: Output XCode version
        run: |
          xcodebuild -version
      - name: Build debug version
        run: |
          make build
